name: Release
run-name: Release ${{ github.event.inputs.tag }}

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag, for example: v0.1.5-experimental"
                required: true
                type: string

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Validate tag
              run: |
                  if [[ ! ${{ github.event.inputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+-experimental$ ]]; then
                      echo "Invalid tag format"
                      exit 1
                  fi

            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: packages/pino-preview/

    release:
        name: Release
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Create branch `release/latest-experimental`
              run: git switch --orphan release/latest-experimental

            - name: Download build arficat
              uses: actions/download-artifact@v4
              with:
                  name: build

            - name: Display structure of downloaded files
              run: ls -R

            - name: Git add
              run: git add .

            - name: Git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "6334521+aarokorhonen@users.noreply.github.com"

            - name: Git commit
              run: git commit -m "Release ${{ github.event.inputs.tag }}"

            - name: Git tag
              run: git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"

            - name: Git push tag
              run: git push origin ${{ github.event.inputs.tag }}

            - name: Git push branch
              run: git push origin release/latest-experimental --force

            - name: Release on GitHub
              uses: softprops/action-gh-release@v1
              with:
                  files: "*"
                  tag_name: ${{ github.event.inputs.tag }}
                  body: |
                      This is an experimental release.
